trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      $(npm bin)/cypress install
      $(npm bin)/cypress run
    displayName: 'Run Cypress tests'
